# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[rust]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[status]
symbol = "✖ "
disabled = false
map_symbol = true
pipestatus = true
